[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
store = "54jF2wtHopafEnsVUbCe1c1Krfcm8jfRjcgrcZ4axsUk"

[programs.mainnet]
store = "54jF2wtHopafEnsVUbCe1c1Krfcm8jfRjcgrcZ4axsUk"

[registry]
url = "https://anchor.projectserum.com/"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
